blueprint:
  name: "Presence Sensor Blueprint"
  description: "Automates lighting based on motion, saves & restores light state."
  domain: automation
  input:
    motion_sensor:
      name: "Motion Sensor"
      description: "Select the motion sensor."
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    lights:
      name: "Lights to Control"
      description: "Choose lights in the room to turn on/off."
      selector:
        entity:
          domain: light
          multiple: true

    delay_minutes:
      name: "Turn-Off Delay (Minutes)"
      description: "Set the delay before turning lights off."
      default: 1
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes

    delay_seconds:
      name: "Turn-Off Delay (Seconds)"
      description: "Additional delay in seconds."
      default: 0
      selector:
        number:
          min: 0
          max: 59
          unit_of_measurement: seconds

    scene_name:
      name: "Scene Name"
      description: "Enter a unique scene name (no spaces, use underscores '_')."
      default: "presence_lights_scene"
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: motion_on

  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: !input delay_minutes
      seconds: !input delay_seconds
    id: motion_off

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: scene.create
            data:
              scene_id: !input scene_name
              snapshot_entities: !input lights
          - service: light.turn_off
            target:
              entity_id: !input lights

      - conditions:
          - condition: trigger
            id: motion_on
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.!input scene_name
          - service: scene.delete
            target:
              entity_id: scene.!input scene_nam
